### ISSUE TITLE
detected dubious ownership in repository

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/ansible-role-deploy-laravel#11]
fatal: detected dubious ownership in repository at '/var/www/intercambio.fflch.usp.br'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /var/www/intercambio.fflch.usp.br\n"}

Resolução:

Essa role muda o dono da pasta para www-data. Uma possível solução é fazer uma task dentro dessa role que volte o dono da pasta para ser root antes da task do git clone. Manualmente deu certo esse procedimento.
@ricardfo consegue implementar essa task?

**Comment by ricardfo** [comment]
Corrigido com o comiit 7fcd377
