### ISSUE TITLE
Reiniciar a fila durante e deploy

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/ansible-role-deploy-laravel#12]
Depois de muito tempo encontrei o problema dos sistemas não estarem enviando email:

https://laracasts.com/discuss/channels/laravel/queue-mail-not-using-env-mail-config

Pode colocar esse comando como parte do deploy, como a última etapa:

`php artisan queue:restart`

**Comment by ricardfo** [comment]
Resolvido com o commit #fe28d82.
